//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouringShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khuyenmai
    {
        public int ID_KM { get; set; }
        public string Giamgia { get; set; }
        public string Motakhuyenmai { get; set; }
        public Nullable<decimal> Phamtramgiamgia { get; set; }
        public System.DateTime Ngaybatdau { get; set; }
        public System.DateTime Ngayketthuc { get; set; }
    }
}
