//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouringShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
            this.Danhgiasanphams = new HashSet<Danhgiasanpham>();
            this.Giohangs = new HashSet<Giohang>();
        }
    
        public int ID_SP { get; set; }
        public string Ten_SP { get; set; }
        public string Motasanpham { get; set; }
        public decimal Gia { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> Lienketdanhmucsanpham { get; set; }
        public string Thuonghieu { get; set; }
        public string Hinhanh { get; set; }
        public Nullable<decimal> Danhgia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danhgiasanpham> Danhgiasanphams { get; set; }
        public virtual Danhmuc Danhmuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Giohang> Giohangs { get; set; }
    }
}
